<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body></body>
</html>

<!-- <script>
  const a = () => {
    return new Promise((resolve, reject) => {
      if (true) {
        resolve("Hello");
      }
    });
  };

  a()
    .then((data) => console.log(data))
    .catch((err) => console.log(err))
</script> -->

<!-- <script>
  //CallBack Hell

  const a = () => {
    return new Promise((resolve, reject) => {
      resolve(true);
    });
  };

  const p = new Promise((resolve, reject) => {
    resolve(true);
  });

  function c() {
    return new Promise((resolve, reject) => {
      resolve(true);
    });
  }

  a()
    .then((data) => {
      console.log(data);
      p.then((data1) => {
        console.log(data1);
        c().then((data2) => {
          console.log(data2);
        });
      });
    })
    .catch((err) => {
      console.log(err);
    })
    .catch((err1) => {
      console.log(err1);
    })
    .catch((err2) => {
      console.log(err2);
    });
</script> -->

<script>
  //asynch await

  const a = () => {
    return new Promise((resolve, reject) => {
      resolve(false);
    });
  };

  const p = new Promise((resolve, reject) => {
    resolve(true);
  });

  function c() {
    return new Promise((resolve, reject) => {
      resolve(true);
    });
  }

  const fun = async () => {
    const aData = await a().catch((err) => console.log(err));
    const bData = await p.catch((err1) => console.log(err1));
    const cData = await c().catch((err2) => console.log(err2));
    // const dData = await d().catch((err3) => console.log(err3));
    console.log({ aData, bData, cData });
  };
  fun();
</script>

<script>
  const a = () => {
    return new Promise((resolve, reject) => {
      reject();
    });
  };
  a().then(function () {
    console.log("sucess");
  });
</script>
